---
name: Build

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check code
        run: |
          sudo apt update
          sudo apt install clang-format
          pip3 install yamllint
          make check
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PlatformIO
        run: pip3 install platformio
      - name: Install Atmel AVR platform
        run: pio platform install atmelavr
      - name: Build code
        run: make build
